package fr.hamtec.listedepersonne

object Data {

    val listePersons = listOf(
        "Lolo David",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo",
        "toto philipe",
        "lili rose",
        "Louis durand",
        "Dupond zozo"
    )
}